version: '2'

services:
    db:
        container_name: lar_mc_db
        image: mysql/mysql-server:5.7
        command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
        ports:
            - 3306:3306
        volumes:
            - "./storage/db:/var/lib/mysql"
        environment:
            TZ:  ${TIMEZONE}
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
    php:
        container_name: lar_mc_php
        build:
            context: docker/php7-fpm
            args:
                TIMEZONE: ${TIMEZONE}
        volumes:
            - ${APP_PATH}:/var/www
    nginx:
        container_name: lar_mc_nginx
        build: docker/nginx
        ports:
            - 80:80
        volumes_from:
            - php
        volumes:
            - ./logs/nginx/:/var/log/nginx